on:
  push:
    branches:
      - beta

name: ðŸš€ Beta Deployment
jobs:
  # CI optimation, run on the changed file only
  changes:
    name: ðŸ”Ž Looking for changes
    runs-on: ubuntu-latest
    outputs:
      comft: ${{ steps.filter.outputs.comft }}
      prven: ${{ steps.filter.outputs.prven }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: beta
          filters: |
            comft:
              - 'comft/**'
            prven:
              - 'prven/**'

  comft:
    name: ðŸŽ‰ Comft Deploy
    needs: changes
    if: ${{ needs.changes.outputs.comft == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: ðŸ”¨ Lookup for the project
        run: cd comft

      - name: Composer PHP 7.4
        uses: php-actions/composer@v6
        with:
          php_version: 7.4
          command: ls && composer install

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.landslide.id
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./comft/
          server-dir: ./api-beta.landslide.id/

  prven:
    name: ðŸŽ‰ Prven Deploy
    needs: changes
    if: ${{ needs.changes.outputs.prven == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: ðŸšš Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: ðŸ”¨ Build Project
        run: |
          cd prven
          npm install
          npm run build
        env:
          REACT_APP_ENV: BETA

      - name: ðŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.landslide.id
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./prven/build/
          server-dir: ./beta.landslide.id/
