on:
  push:
    branches:
      - beta

name: ğŸš€ Beta Deployment
jobs:
  # CI optimation, run on the changed file only
  changes:
    name: ğŸ” Looking for changes
    runs-on: ubuntu-latest
    outputs:
      comft: ${{ steps.filter.outputs.comft }}
      prven: ${{ steps.filter.outputs.prven }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          base: beta
          filters: |
            comft:
              - 'comft/**'
            prven:
              - 'prven/**'

  comft:
    name: ğŸ‰ Comft Deploy
    needs: changes
    if: ${{ needs.changes.outputs.comft == 'true' || secrets.COMFT_FORCE_BUILD == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: ğŸ”¨ Installing dependencies
        run: |
          cd comft
          composer install --prefer-dist
          php artisan migrate

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.landslide.id
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./comft/
          server-dir: ./api-beta.landslide.id/

  prven:
    name: ğŸ‰ Prven Deploy
    needs: changes
    if: ${{ needs.changes.outputs.prven == 'true' || secrets.PRVEN_FORCE_BUILD == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: ğŸšš Get latest code
        uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v2-beta
        with:
          node-version: "12"

      - name: ğŸ”¨ Build Project
        run: |
          cd prven
          npm install
          npm run build
        env:
          REACT_APP_ENV: BETA

      - name: ğŸ“‚ Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ftp.landslide.id
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          local-dir: ./prven/build/
          server-dir: ./beta.landslide.id/
